# Generated by Django 5.2.12 on 2026-03-20 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='r_student',
            new_name='portal',
        ),
    ]
