# Generated by Django 5.2.5 on 2026-03-21 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_rename_r_student_portal'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='portal',
            new_name='user',
        ),
    ]
