# Generated by Django 5.2.5 on 2026-03-21 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_rename_portal_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='user',
            new_name='registers',
        ),
    ]
