# Generated by Django 5.2.5 on 2026-03-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_rename_user_registers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('expiry_date', models.DateField()),
                ('description', models.TextField()),
                ('notice_pdf', models.FileField(blank=True, null=True, upload_to='notices/')),
            ],
        ),
    ]
